name: PDF deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    name: Build and deploy release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Fetching sources from repository
        uses: actions/checkout@v2
      - name: Setting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Installing native dependencies
        run: |
          sudo apt install fonts-dejavu texlive-full latexmk xindy
      - name: Building PDF using Sphinx
        run: |
          make latexpdf
      - name: Uploading built PDF artifact to releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/latex/fedora-faq-ru.pdf
